### ISSUE TITLE
conditional Mean need update

### ISSUE THREAD

**Issue by esclapez** [AMReX-Combustion/PeleAnalysis#11]
Also, I fixed a few minor errors that popped up during compile time for ```conditionalMeans```. Just a few changes in the header files, adding a few ```std::``` namespaces:
1. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L10 changed to ```#include <AMReX_PlotFileUtil.H>```
2. Removed https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L11
3. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L122 becomes ```Vector<std::string> compNames;```
4. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L130 becomes ```std::vector```
5. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L327 becomes ```std::string variables...```

_Originally posted by @RSuryaNarayan in https://github.com/AMReX-Combustion/PeleAnalysis/issues/6#issuecomment-1026524230_

**Comment by esclapez** [comment]
I'm pretty sure other execs have similar issues, so I'll comb through and make the fixes.

**Comment by RSuryaNarayan** [comment]
yeah, sure @esclapez. Maybe because ```amrex``` underwent some updates recently. These changes for ```conditionalMeans``` work. I tested it on a plotfile.

**Comment by esclapez** [comment]
This and similar issues in other execs are fixed in #12
