### ISSUE TITLE
Segfaults while trying to append data to plot file in grad.cpp

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleAnalysis#6]
I am trying to append data to a plot file using the script ```grad.cpp```. I use the following inputs ```inp.2d``` after I have an executable:
```
infile = pltfile
gradVar = Temp
finestLevel = 2
is_per = 0 0 0
appendPlotFile= 1
```
The output I get after I do ```mpirun -np 4 ./grad2d.gnu.MPI.ex inp.2d``` reads as follows: 

```
MPI initialized with 4 MPI processes
MPI initialized with thread support level 0
AMReX (21.02-18-g7742e1c99f5e-dirty) initialized
Doing FillVar at lev: 0
Doing FillVar at lev: 1
Doing FillVar at lev: 2
Segfault
See Backtrace.1 file for details
```
I tried to trace it back to the exact line at which it breaks away and it looks like it might be [L#163](https://github.com/AMReX-Combustion/PeleAnalysis/blob/2af3fb931eb6567572913e38a1ff71e246fe1dcc/Src/grad.cpp#L163)

Anything wrong I might be doing?

**Comment by drummerdoc** [comment]
Does it work if you don't append but just make a new plot file for the grad components?  The append stuff is a hack that causes other difficulties later anyway.

**Comment by RSuryaNarayan** [comment]
yes perfectly @drummerdoc . I only face an issue when I try to append it. 

Appending stuff seems like a really good feature however.

**Comment by drummerdoc** [comment]
Well, you can combine plot files after the fact.  It does require that all the data is read in and dumped out

**Comment by RSuryaNarayan** [comment]
Makes sense. Read them as separate files and merge them into a single multifab. Thanks!

**Comment by RSuryaNarayan** [comment]
@drummerdoc I run into segfaults the first time I try to append as well.

**Comment by RSuryaNarayan** [comment]
Maybe we can have a separate script that does just this: takes "n" plot files and merge them all into a single one "plot_merged" and that way we can avoid renaming the header.

**Comment by drummerdoc** [comment]
Yeah, it's probably just something that needs updating...it certainly used to work and is probably just something dumb.  But my point is that the append thing, even when it works, is a source of confusion because of what I said above.  I put in that capability for when the plot files are massive and wanted to avoid reading/writing TB of data just to add one more component.

**Comment by drummerdoc** [comment]
Use combinePlts.cpp to do what you want.

**Comment by drummerdoc** [comment]
Ahh, probably missing an "if (amex::ParallelDescriptor::IOProcessor()) {...}" around the code that writes the new Header of moves the old one out of the way or something.  I'll try to get to fixing that someday, but life is a bit busy these days....thanks for reporting

**Comment by RSuryaNarayan** [comment]
@drummerdoc thanks for the reply. No worries I'll try fixing with the hints you gave!

**Comment by drummerdoc** [comment]
If you added the ability to auto-generated MultiFab file names that were guaranteed not to clash with ones already being used, that would eliminate the worst hack about what I did, I think.

**Comment by RSuryaNarayan** [comment]
Sorry to bother again on this, but I find the grad tool gives segfaults with plot files that are periodic along a single direction. The acoustic pulse case in [EB-C9](https://github.com/AMReX-Combustion/PeleC/tree/development/Exec/RegTests/EB-C9) for instance. Specifically, the segfault occurs when we fill the ghost cells using ``FillBoundary``. 
https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/grad.cpp#L133

**Comment by drummerdoc** [comment]
Hmmm, I'll try to look, but maybe I can convince @esclapez to have a look as well.

**Comment by esclapez** [comment]
You might ! I'll have a look at it. I'll probably switch to MLMG as done in the curvature.

**Comment by drummerdoc** [comment]
Ahh yes, good point!

**Comment by RSuryaNarayan** [comment]
Thank you so much for your prompt replies!

**Comment by esclapez** [comment]
@RSuryaNarayan can you give [this branch](https://github.com/AMReX-Combustion/PeleAnalysis/tree/updateGrad) a try ? An example input file is provided in `Src/InputsSamples/inputs.grad`.

**Comment by RSuryaNarayan** [comment]
@esclapez This branch works perfectly well. I tested it with both 2d and 3d plotfiles. Thanks a ton!

**Comment by esclapez** [comment]
Awesome! Merging in Master in #10 .

**Comment by RSuryaNarayan** [comment]
Also, I fixed a few minor errors that popped up during compile time for ```conditionalMeans```. Just a few changes in the header files, adding a few ```std::``` namespaces:
1. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L10 changed to ```#include <AMReX_PlotFileUtil.H>```
2. Removed https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L11
3. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L122 becomes ```Vector<std::string> compNames;```
4. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L130 becomes ```std::vector```
5. https://github.com/AMReX-Combustion/PeleAnalysis/blob/0f30b8523ca40a088b799d0fabab5994f6759326/Src/conditionalMean.cpp#L327 becomes ```std::string variables...```
