### ISSUE TITLE
problem compiling model-specific analysis tool

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleAnalysis#7]
Hello, 

I am trying to compile ```PeleAnalysis/Src/ModelSpecificAnalysis/plotTransportCoeff.cpp``` and I had to make the following changes to the ```GNUMakefile``` in the above directory to point to the right submodules: 

```
PELE_ANALYSIS_HOME ?= /home/suryanarayan/PeleAnalysis
PELE_PHYSICS_HOME ?= /home/suryanarayan/PeleC/Submodules/PelePhysics
AMREX_HOME ?= /home/suryanarayan/PeleC/Submodules/AMReX
```
Basically, I used my local PeleC submodules to point to the AMReX and PelePhysics folders instead of installing them again. 

I get the following errors while trying to compile ```plotTransportCoeff.cpp```:
```
plotTransportCoeff.cpp:13:10: fatal error: mechanism.h: No such file or directory
   13 | #include <mechanism.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

```
When I changed it to ```mechanism.H``` instead of ```mechanism.h``` I get:
```
plotTransportCoeff.cpp:14:10: fatal error: chemistry_file.H: No such file or directory
   14 | #include <chemistry_file.H>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
I comment that line and end-up with:
```
plotTransportCoeff.cpp:17:10: fatal error: Transport_F.H: No such file or directory
   17 | #include <Transport_F.H>
      |          ^~~~~~~~~~~~~~~
```
Is it possibly an environment issue?

**Comment by drummerdoc** [comment]
Sorry for the delay in response..your questions came at an unusually busy time (ECP review, plus...).  I will fix this asap and get back to you.

**Comment by RSuryaNarayan** [comment]
@drummerdoc Thank you so much for your reply amidst your busy schedule.

**Comment by esclapez** [comment]
Hi Surya,

Could you give a try to [this branch](https://github.com/AMReX-Combustion/PeleAnalysis/tree/updateDependencies). Note that this entire folder is pretty outdated and we will have to rewrite it entirely at some point.

Lucas

**Comment by RSuryaNarayan** [comment]
Hello Dr.Lucas @esclapez 

Thank you very much for sorting this out. This branch works perfectly fine. 

Surya
